config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'code#index'
  resources :code

end

app/models/code.rb
require 'will_paginate'

class Code < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/code_controller.rb
class CodeController < ApplicationController
  def index
    @resultOrig = Code.all
    @result = Code.all.paginate(:page => params[:page], :per_page => 8)
    @count = Code.count
    @name = current_user.name
    @counter = 1 + (@result.current_page-1)*8
  end

  def new
    @code = Code.new
    @kinds = ["Line", "Block", "Full Program"]
    @languages = ["Java", "JavaScript", "Ruby", "Pascal", "Swift", "HTML", "CSS"]
  end

  def create
    @code = Code.create(code_params)
    @code.user = current_user
    @code.save
    redirect_to code_index_path
  end

  def show
    @code = Code.find(params[:id])
    @user = @code.user
  end

  def destroy
    @result = Code.all
    @result.destroy_all
    redirect_to code_index_path
  end

  def edit
    @code = Code.find(params[:id])
    @kinds = ["Line", "Block", "Full Program"]
    @languages = ["Java", "JavaScript", "Ruby", "Pascal", "Swift", "HTML", "CSS"]
  end

  def update
    @code = Code.find(params[:id])
    @code.update_attributes(code_params)
    redirect_to code_index_path(@result)
  end

  private

  def code_params
    params.require(:code).permit(:kind, :language, :purpose, :content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/code/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Editing Entries</h1>
    <div class="panel panel-default devise-bs">
      <div class="panel-body">
        <%= form_for @code, url: {action: "update"}, method: :put do |f| %>
          <div class="form-group">
            <%= f.label :kind %>
            <%= f.select :kind, @kinds %>
          </div>
          <div class="form-group">
            <%= f.label :language %>
            <%= f.select :language, @languages %>
          </div>
          <div class="form-group">
            <%= f.label :purpose %>
            <%= f.text_field :purpose, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, autofocus: true, class: "form-control" %>
          </div>
          <%= f.submit t('.update', :default => "Update"), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
</div>

app/views/code/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Welcome <%= @name %>!</h1>
  <h2>Code Library</h2>
  <h3>Number of code inputs:
    <%=@count%>
  </h3>
  <h3>
    <button class="btn btn-default"><%= link_to "Add Code", new_code_path%></button>
    <button class="btn btn-default"><%= link_to "Delete All", code_path(@result), method: :delete%></button>
  </h3>

  <%@result.each do |result|%>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">Code #<%=@counter%></div>
        <div class="panel-body">
          <p><strong>Type:</strong> <%=result.kind%></p>
          <p><strong>Language:</strong> <%=result.language%></p>
          <p><strong>Purpose:</strong> <%=result.purpose%></p>
          <p><%= link_to "Show Code", code_path(result)%></p>
          <button class="btn btn-warning-bg"><%= link_to "Edit", edit_code_path(result)%></button>
        </div>
      </div>
    </div>
    <% @counter = @counter + 1 %>
  <% end %>
  <div class="col-md-5 col-md-offset-5">
    <%= will_paginate @result %>
  </div>
  <div class="col-xs-12" style="height:30px;"></div>
</div>

app/views/code/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New Entry</h1>
    <div class="panel panel-default devise-bs">
      <div class="panel-body">
        <%= form_for @code, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
          <div class="form-group">
            <%= f.label :kind %>
            <%= f.select :kind, @kinds %>
          </div>
          <div class="form-group">
            <%= f.label :language %>
            <%= f.select :language, @languages %>
          </div>
          <div class="form-group">
            <%= f.label :purpose %>
            <%= f.email_field :purpose, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.email_field :content, autofocus: true, class: "form-control" %>
          </div>
          <%= f.submit t('.create', :default => "Create"), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
</div>

app/views/code/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>User</h2>
    <p><%= @code.user.name %></p>
  <h2>Kind</h2>
    <p><%= @code.kind %></p>
  <h2>Language</h2>
    <p><%= @code.language %></p>
  <h2>Purpose</h2>
    <p><%= @code.purpose %></p>
  <h2>Content</h2>
    <p><%= @code.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <a class="navbar-brand" href="#">
            <%= image_tag("code.png", size: "30x30") %>
          </a>
          <%= link_to "Codes", code_index_path, :class => "navbar-brand"%>
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
              <li>
              <%= link_to "Edit Profile", edit_user_registration_path(@user)%>
              </li>
              <li>
              <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li>
              <%= link_to "Sign Up", new_user_registration_path(@user)%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <%= yield %>

  <footer class="footer"%>
    <div class="container">
      <p class="text-muted" align="center">2016, Arrian Ebrahimi</p>
      </div>
  </footer>
</body>
</html>

<style>
  .footer {
    position: fixed;
    bottom: 0;
    height: 30px;
    background: #F3F3F3;
    width: 100%;
  }
</style>